write('ismotherinlaw(wd, ft)'),
once(ismotherinlaw(wd, ft)).
write('isdaughterinlaw(wd, ft)'),
once(isdaughterinlaw(wd, ft)).
write('ismother(sd, me)'),
once(ismother(sd, me)).
write('isfather(me, sd)'),
once(isfather(me, sd)).
write('isbrother(me, b2)'),
once(isbrother(me, b2)).
write('isgrandmother(wd, b2)'),
once(isgrandmother(wd, b2)).
write('isgrandfather(me, b2)'),
once(isgrandfather(me, b2)).
write('issister(sd, b1)'),
once(issister(sd, b1)).
write('isgrandmother(sd, b1)'),
once(isgrandmother(sd, b1)).
write('isbrotherinlaw(ft, b1)'),
once(isbrotherinlaw(ft, b1)).
write('isbrother(me, b1)'),
once(isbrother(me, b1)).
write('isaunt(wd, b1)'),
once(isaunt(wd, b1)).
write('isgrandfather(ft, b1)'),
once(isgrandfather(ft, b1)).
write('isgrandfather(me, me)'),
once(isgrandfather(me, me)).
